-- ============================================================
-- Questionário Bizu v4.35 — comunidade, suporte e tópicos.
-- Execute uma única vez no SQL Editor do Supabase antes do deploy.
-- ============================================================

create table if not exists public.chat_salas (
  id uuid primary key default gen_random_uuid(),
  nome text not null check (char_length(trim(nome)) between 3 and 50),
  tipo text not null default 'publica' check (tipo in ('publica', 'privada')),
  criador_id uuid references public.usuarios(id) on delete set null,
  sistema boolean not null default false,
  ativa boolean not null default true,
  criado_em timestamptz not null default now()
);

create table if not exists public.chat_sala_membros (
  sala_id uuid not null references public.chat_salas(id) on delete cascade,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  papel text not null default 'membro' check (papel in ('criador', 'membro')),
  adicionado_em timestamptz not null default now(),
  primary key (sala_id, usuario_id)
);

create table if not exists public.chat_mensagens (
  id bigint generated by default as identity primary key,
  sala_id uuid not null references public.chat_salas(id) on delete cascade,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  mensagem text not null check (char_length(trim(mensagem)) between 1 and 400),
  criado_em timestamptz not null default now()
);

create table if not exists public.suporte_conversas (
  id uuid primary key default gen_random_uuid(),
  usuario_id uuid not null unique references public.usuarios(id) on delete cascade,
  status text not null default 'aberta' check (status in ('aberta', 'fechada')),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.suporte_mensagens (
  id bigint generated by default as identity primary key,
  conversa_id uuid not null references public.suporte_conversas(id) on delete cascade,
  autor_id uuid not null references public.usuarios(id) on delete cascade,
  mensagem text not null check (char_length(trim(mensagem)) between 1 and 1000),
  criado_em timestamptz not null default now()
);

create table if not exists public.topicos_comunidade (
  id bigint generated by default as identity primary key,
  autor_id uuid not null references public.usuarios(id) on delete cascade,
  titulo text not null check (char_length(trim(titulo)) between 5 and 100),
  conteudo text not null check (char_length(trim(conteudo)) between 5 and 2400),
  categoria text not null default 'duvida' check (categoria in ('duvida', 'discussao', 'estudo', 'aviso')),
  fechado boolean not null default false,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.topico_respostas (
  id bigint generated by default as identity primary key,
  topico_id bigint not null references public.topicos_comunidade(id) on delete cascade,
  autor_id uuid not null references public.usuarios(id) on delete cascade,
  conteudo text not null check (char_length(trim(conteudo)) between 1 and 1600),
  criado_em timestamptz not null default now()
);

create index if not exists chat_salas_tipo_ativa_idx on public.chat_salas(tipo, ativa, criado_em desc);
create index if not exists chat_sala_membros_usuario_idx on public.chat_sala_membros(usuario_id, sala_id);
create index if not exists chat_mensagens_sala_criado_idx on public.chat_mensagens(sala_id, criado_em desc);
create index if not exists suporte_conversas_atualizado_idx on public.suporte_conversas(status, atualizado_em desc);
create index if not exists suporte_mensagens_conversa_idx on public.suporte_mensagens(conversa_id, criado_em);
create index if not exists topicos_comunidade_atualizado_idx on public.topicos_comunidade(fechado, atualizado_em desc);
create index if not exists topico_respostas_topico_idx on public.topico_respostas(topico_id, criado_em);

insert into public.chat_salas (id, nome, tipo, criador_id, sistema, ativa)
values ('00000000-0000-4000-8000-000000000001', 'Geral', 'publica', null, true, true)
on conflict (id) do update set nome = excluded.nome, tipo = 'publica', sistema = true, ativa = true;

alter table public.chat_salas enable row level security;
alter table public.chat_sala_membros enable row level security;
alter table public.chat_mensagens enable row level security;
alter table public.suporte_conversas enable row level security;
alter table public.suporte_mensagens enable row level security;
alter table public.topicos_comunidade enable row level security;
alter table public.topico_respostas enable row level security;

revoke all on public.chat_salas, public.chat_sala_membros, public.chat_mensagens,
  public.suporte_conversas, public.suporte_mensagens,
  public.topicos_comunidade, public.topico_respostas from public, anon, authenticated;

grant select, insert, update, delete on public.chat_salas, public.chat_sala_membros, public.chat_mensagens,
  public.suporte_conversas, public.suporte_mensagens,
  public.topicos_comunidade, public.topico_respostas to service_role;

grant usage, select on sequence public.chat_mensagens_id_seq,
  public.suporte_mensagens_id_seq, public.topicos_comunidade_id_seq,
  public.topico_respostas_id_seq to service_role;
