-- Questionário Bizu v4.44.1 · XP, missões e central de notificações.
-- Execute uma única vez no SQL Editor do Supabase.
-- CORREÇÃO 4.44.1: a coluna usuarios.xp_total é qualificada pelo alias u.
begin;

alter table public.usuarios
  add column if not exists xp_total bigint not null default 0,
  add column if not exists xp_bonus_plano integer not null default 0,
  add column if not exists xp_migrado_em timestamptz;

alter table public.usuarios drop constraint if exists usuarios_xp_total_check;
alter table public.usuarios add constraint usuarios_xp_total_check check (xp_total >= 0);
alter table public.usuarios drop constraint if exists usuarios_xp_bonus_plano_check;
alter table public.usuarios add constraint usuarios_xp_bonus_plano_check check (xp_bonus_plano between 0 and 2500);

create table if not exists public.xp_eventos (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  chave text not null,
  tipo text not null,
  pontos integer not null check (pontos > 0),
  detalhes jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now(),
  unique (usuario_id, chave)
);

create table if not exists public.notificacoes (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  tipo text not null check (tipo in ('suporte','chat_privado','vencimento','missao','patente','plano','sistema')),
  titulo text not null check (char_length(titulo) between 1 and 80),
  mensagem text not null check (char_length(mensagem) between 1 and 240),
  acao text,
  referencia_id text,
  chave text not null,
  lida_em timestamptz,
  criado_em timestamptz not null default now(),
  unique (usuario_id, chave)
);

create index if not exists xp_eventos_usuario_criado_idx on public.xp_eventos(usuario_id, criado_em desc);
create index if not exists notificacoes_usuario_criado_idx on public.notificacoes(usuario_id, criado_em desc);
create index if not exists notificacoes_nao_lidas_idx on public.notificacoes(usuario_id, criado_em desc) where lida_em is null;

alter table public.xp_eventos enable row level security;
alter table public.notificacoes enable row level security;
revoke all on public.xp_eventos, public.notificacoes from public, anon, authenticated;
grant select, insert, update, delete on public.xp_eventos, public.notificacoes to service_role;
grant usage, select on sequence public.xp_eventos_id_seq, public.notificacoes_id_seq to service_role;

create or replace function public.conceder_xp(
  p_usuario_id uuid,
  p_chave text,
  p_tipo text,
  p_pontos integer,
  p_detalhes jsonb default '{}'::jsonb
) returns table(aplicado boolean, xp_total bigint)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
#variable_conflict use_variable
declare
  v_id bigint;
  v_total bigint;
begin
  if p_usuario_id is null or nullif(trim(p_chave), '') is null or p_pontos <= 0 then
    raise exception 'Evento de XP inválido.';
  end if;

  insert into public.xp_eventos(usuario_id, chave, tipo, pontos, detalhes)
  values (p_usuario_id, trim(p_chave), left(coalesce(nullif(trim(p_tipo), ''), 'estudo'), 40), p_pontos, coalesce(p_detalhes, '{}'::jsonb))
  on conflict (usuario_id, chave) do nothing
  returning id into v_id;

  if v_id is not null then
    update public.usuarios as u
       set xp_total = u.xp_total + p_pontos
     where u.id = p_usuario_id
    returning u.xp_total into v_total;
  else
    select u.xp_total into v_total from public.usuarios u where u.id = p_usuario_id;
  end if;

  return query select v_id is not null, coalesce(v_total, 0);
end;
$$;

revoke all on function public.conceder_xp(uuid,text,text,integer,jsonb) from public, anon, authenticated;
grant execute on function public.conceder_xp(uuid,text,text,integer,jsonb) to service_role;

-- Retroativo: cada acerto antigo vale 10 XP. Esse piso mantém exatamente a
-- patente anterior, inclusive para usuários com muitas revisões.
with historico as (
  select u.id, count(r.id) filter (where r.acertou and not r.pulada and r.resposta_marcada is not null)::integer as pontos_base
  from public.usuarios u
  left join public.respostas r on r.usuario_id = u.id
  where u.xp_migrado_em is null
  group by u.id
)
insert into public.xp_eventos(usuario_id, chave, tipo, pontos, detalhes)
select id, 'retroativo-v1', 'retroativo', pontos_base * 10, jsonb_build_object('regra', '10 XP por acerto anterior')
from historico where pontos_base > 0
on conflict (usuario_id, chave) do nothing;

with historico as (
  select u.id, count(r.id) filter (where r.acertou and not r.pulada and r.resposta_marcada is not null)::bigint * 10 as xp
  from public.usuarios u
  left join public.respostas r on r.usuario_id = u.id
  where u.xp_migrado_em is null
  group by u.id
)
update public.usuarios u
set xp_total = greatest(u.xp_total, h.xp), xp_migrado_em = now()
from historico h where h.id = u.id;

create or replace function public.sincronizar_bonus_plano_xp() returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_alvo integer;
  v_diferenca integer;
begin
  v_alvo := case
    when new.perfil in ('admin','supremo') then 0
    when new.vip or new.plano_atual = 'vitalicio' then 2500
    when new.plano_atual = 'trimestral' then 1200
    when new.premium or new.plano_atual = 'mensal' then 500
    else 0
  end;
  v_diferenca := greatest(v_alvo - coalesce(new.xp_bonus_plano, 0), 0);

  if v_diferenca > 0 then
    perform public.conceder_xp(new.id, 'bonus-plano-' || v_alvo, 'plano', v_diferenca,
      jsonb_build_object('bonus_total', v_alvo, 'plano', new.plano_atual));
    update public.usuarios set xp_bonus_plano = v_alvo where id = new.id;
    insert into public.notificacoes(usuario_id,tipo,titulo,mensagem,acao,chave)
    values (new.id,'plano','Bônus de assinatura',
      'Seu plano concedeu ' || v_diferenca || ' XP de bônus permanente.','missoes','plano-xp-' || v_alvo)
    on conflict (usuario_id,chave) do nothing;
  end if;
  return null;
end;
$$;
revoke all on function public.sincronizar_bonus_plano_xp() from public, anon, authenticated;

drop trigger if exists usuarios_bonus_plano_xp_insert on public.usuarios;
drop trigger if exists usuarios_bonus_plano_xp_update on public.usuarios;
create trigger usuarios_bonus_plano_xp_insert
after insert on public.usuarios
for each row execute function public.sincronizar_bonus_plano_xp();
create trigger usuarios_bonus_plano_xp_update
after update of vip,premium,plano_atual,perfil on public.usuarios
for each row execute function public.sincronizar_bonus_plano_xp();

-- Concede o bônus uma única vez aos assinantes atuais.
update public.usuarios set plano_atual = plano_atual
where perfil = 'aluno' and (vip or premium or plano_atual in ('mensal','trimestral','vitalicio'));

drop view if exists public.ranking_usuarios;
create view public.ranking_usuarios as
select
  u.id as usuario_id, u.nome, u.usuario, u.perfil, u.vip, u.xp_total,
  count(distinct r.sessao_id)::bigint as sessoes,
  count(r.id)::bigint as respondidas,
  count(r.id) filter (where r.acertou)::bigint as acertos,
  case when count(r.id) > 0
    then round((count(r.id) filter (where r.acertou))::numeric / count(r.id)::numeric * 100)::integer
    else 0 end as percentual,
  u.premium, u.plano_atual
from public.usuarios u
left join public.respostas r on r.usuario_id = u.id and r.pulada = false and r.resposta_marcada is not null
group by u.id, u.nome, u.usuario, u.perfil, u.vip, u.xp_total, u.premium, u.plano_atual;

comment on view public.ranking_usuarios is
  'Ranking geral por acertos, com XP independente para progressão de patentes.';
revoke all on public.ranking_usuarios from public, anon, authenticated;
grant select on public.ranking_usuarios to service_role;

commit;
