-- Questionário Bizu v4.6
-- Presença online + chat temporário/efêmero.
-- As mensagens não formam histórico permanente: a aplicação limpa a sala
-- quando não há mais usuários ativos e também remove mensagens antigas por segurança.

create table if not exists public.presencas_online (
  usuario_id uuid primary key references public.usuarios(id) on delete cascade,
  visto_em timestamptz not null default now(),
  atividade_em timestamptz not null default now()
);

create table if not exists public.chat_temporario (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  mensagem text not null check (char_length(trim(mensagem)) between 1 and 400),
  criado_em timestamptz not null default now()
);

create index if not exists idx_presencas_online_visto_em
  on public.presencas_online(visto_em desc);

create index if not exists idx_presencas_online_atividade_em
  on public.presencas_online(atividade_em desc);

create index if not exists idx_chat_temporario_criado_em
  on public.chat_temporario(criado_em desc);

alter table public.presencas_online enable row level security;
alter table public.chat_temporario enable row level security;

-- O navegador nunca acessa estas tabelas diretamente. Toda leitura/escrita
-- passa pelas rotas autenticadas da aplicação usando service_role.
revoke all on public.presencas_online from anon, authenticated;
revoke all on public.chat_temporario from anon, authenticated;
grant select, insert, update, delete on public.presencas_online to service_role;
grant select, insert, update, delete on public.chat_temporario to service_role;
grant usage, select on sequence public.chat_temporario_id_seq to service_role;
