create extension if not exists pgcrypto;

create table if not exists public.usuarios (
  id uuid primary key default gen_random_uuid(),
  usuario text not null unique check (usuario ~ '^[a-zA-Z0-9._-]{3,30}$'),
  senha_hash text not null,
  nome text not null,
  perfil text not null default 'aluno' check (perfil in ('supremo','admin','aluno')),
  ativo boolean not null default true,
  status_aprovacao text not null default 'pendente' check (status_aprovacao in ('pendente','aprovado','negado')),
  criado_em timestamptz not null default now(),
  ultimo_acesso timestamptz,
  validade_ate timestamptz,
  desativado_por_validade boolean not null default false,
  criado_por_admin_id uuid references public.usuarios(id) on delete set null,
  aprovado_por_admin_id uuid references public.usuarios(id) on delete set null,
  responsavel_admin_id uuid references public.usuarios(id) on delete set null,
  vip boolean not null default false,
  premium boolean not null default false,
  vip_desde timestamptz,
  acesso_teste boolean not null default false,
  teste_expira_em timestamptz
  ,whatsapp text check (whatsapp is null or whatsapp ~ '^55[0-9]{10,11}$')
  ,cadastro_device_hash text check (cadastro_device_hash is null or cadastro_device_hash ~ '^[a-f0-9]{64}$')
  ,sessao_ativa_device_hash text check (sessao_ativa_device_hash is null or sessao_ativa_device_hash ~ '^[a-f0-9]{64}$')
);

create table if not exists public.disciplinas (
  id text primary key,
  nome text not null,
  descricao text,
  ordem integer not null default 0,
  ativo boolean not null default true
);

create table if not exists public.capitulos (
  id bigint generated by default as identity primary key,
  disciplina_id text not null references public.disciplinas(id) on delete cascade,
  indice integer not null,
  nome text not null,
  ativo boolean not null default true,
  unique (disciplina_id, indice)
);

create table if not exists public.questoes (
  id bigint generated by default as identity primary key,
  disciplina_id text not null references public.disciplinas(id),
  capitulo_id bigint not null references public.capitulos(id),
  tipo text not null default 'multipla_escolha' check (tipo in ('multipla_escolha','certo_errado')),
  enunciado text not null,
  alternativas jsonb not null check (jsonb_array_length(alternativas) between 2 and 5),
  resposta_correta smallint not null check (resposta_correta between 0 and 4),
  resolucao text not null,
  dificuldade text not null default 'media' check (dificuldade in ('facil','media','dificil')),
  fonte text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.sessoes (
  id uuid primary key default gen_random_uuid(),
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  disciplina_id text references public.disciplinas(id),
  capitulo_id bigint references public.capitulos(id) on delete set null,
  total integer not null default 0,
  respondidas integer not null default 0,
  acertos integer not null default 0,
  puladas integer not null default 0,
  percentual integer not null default 0,
  questoes_ids bigint[] not null default '{}'::bigint[]
    check (cardinality(questoes_ids) between 0 and 5000),
  iniciada_em timestamptz not null default now(),
  finalizada_em timestamptz
);

create table if not exists public.respostas (
  id bigint generated by default as identity primary key,
  sessao_id uuid not null references public.sessoes(id) on delete cascade,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  questao_id bigint references public.questoes(id) on delete set null,
  resposta_marcada smallint check (resposta_marcada between 0 and 4),
  acertou boolean not null default false,
  pulada boolean not null default false,
  respondida_em timestamptz not null default now(),
  questao_enunciado text,
  questao_alternativas jsonb,
  questao_resposta_correta smallint,
  questao_resolucao text,
  disciplina_id_snapshot text,
  disciplina_nome_snapshot text,
  capitulo_id_snapshot bigint,
  capitulo_nome_snapshot text,
  unique(sessao_id, questao_id)
);

create index if not exists idx_questoes_filtro on public.questoes(disciplina_id, capitulo_id, ativo);
create index if not exists idx_sessoes_usuario on public.sessoes(usuario_id, finalizada_em desc);
create index if not exists idx_respostas_usuario on public.respostas(usuario_id, respondida_em desc);
create index if not exists idx_respostas_usuario_questao_recente on public.respostas(usuario_id, questao_id, respondida_em desc) where pulada = false;
create index if not exists idx_usuarios_responsavel_admin on public.usuarios(responsavel_admin_id);
create index if not exists idx_usuarios_vip on public.usuarios(vip) where vip = true;
create index if not exists idx_usuarios_teste_expira_em on public.usuarios(teste_expira_em) where acesso_teste = true and teste_expira_em is not null;

alter table public.usuarios enable row level security;
alter table public.disciplinas enable row level security;
alter table public.capitulos enable row level security;
alter table public.questoes enable row level security;
alter table public.sessoes enable row level security;
alter table public.respostas enable row level security;

create table if not exists public.auditoria_admin (
  id bigint generated always as identity primary key,
  ator_id uuid references public.usuarios(id) on delete set null,
  acao text not null check (char_length(acao) between 3 and 80),
  alvo_tipo text not null check (alvo_tipo in ('usuario','plano','pagamento','sistema')),
  alvo_id text,
  detalhes jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now()
);
create index if not exists auditoria_admin_criado_em_idx on public.auditoria_admin(criado_em desc);
create index if not exists auditoria_admin_ator_idx on public.auditoria_admin(ator_id, criado_em desc);
alter table public.auditoria_admin enable row level security;
revoke all on public.auditoria_admin from public, anon, authenticated;
grant select, insert, delete on public.auditoria_admin to service_role;
grant usage, select on sequence public.auditoria_admin_id_seq to service_role;

-- Nenhuma política pública é criada. O acesso ocorre somente pelas Netlify Functions
-- usando a chave service_role mantida em variável de ambiente.


-- v4.3: snapshot automático de respostas para preservar histórico após substituições.
create or replace function public.preencher_snapshot_resposta()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.questao_id is null then return new; end if;
  select q.enunciado, q.alternativas, q.resposta_correta, q.resolucao,
         q.disciplina_id, d.nome, q.capitulo_id, c.nome
    into new.questao_enunciado, new.questao_alternativas, new.questao_resposta_correta,
         new.questao_resolucao, new.disciplina_id_snapshot, new.disciplina_nome_snapshot,
         new.capitulo_id_snapshot, new.capitulo_nome_snapshot
  from public.questoes q
  left join public.disciplinas d on d.id = q.disciplina_id
  left join public.capitulos c on c.id = q.capitulo_id
  where q.id = new.questao_id;
  return new;
end;
$$;

create trigger trg_respostas_snapshot
before insert or update of questao_id on public.respostas
for each row execute function public.preencher_snapshot_resposta();

revoke execute on function public.preencher_snapshot_resposta()
from public, anon, authenticated;

create or replace view public.ranking_usuarios as
select
  u.id as usuario_id,
  u.nome,
  u.usuario,
  u.perfil,
  u.vip,
  u.premium,
  count(distinct r.sessao_id)::bigint as sessoes,
  count(r.id)::bigint as respondidas,
  count(r.id) filter (where r.acertou)::bigint as acertos,
  case when count(r.id) > 0
    then round((count(r.id) filter (where r.acertou))::numeric / count(r.id)::numeric * 100)::integer
    else 0 end as percentual
from public.usuarios u
join public.respostas r on r.usuario_id = u.id
where r.pulada = false and r.resposta_marcada is not null
group by u.id, u.nome, u.usuario, u.perfil, u.vip, u.premium;

-- v4.3: substituição transacional de disciplina.
create or replace function public.substituir_disciplina_completa(
  p_disciplina jsonb,
  p_capitulos jsonb,
  p_questoes jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id text;
  v_capitulos integer := 0;
  v_questoes integer := 0;
begin
  v_id := nullif(trim(p_disciplina->>'id'), '');
  if v_id is null then raise exception 'Disciplina inválida.'; end if;

  insert into public.disciplinas (id, nome, descricao, ordem, ativo)
  values (
    v_id,
    p_disciplina->>'nome',
    nullif(p_disciplina->>'descricao', ''),
    coalesce((p_disciplina->>'ordem')::integer, 0),
    coalesce((p_disciplina->>'ativo')::boolean, true)
  )
  on conflict (id) do update set
    nome = excluded.nome,
    descricao = excluded.descricao,
    ordem = excluded.ordem,
    ativo = excluded.ativo;

  delete from public.questoes where disciplina_id = v_id;
  delete from public.capitulos where disciplina_id = v_id;

  insert into public.capitulos (disciplina_id, indice, nome, ativo)
  select v_id, (item->>'indice')::integer, item->>'nome', coalesce((item->>'ativo')::boolean, true)
  from jsonb_array_elements(coalesce(p_capitulos, '[]'::jsonb)) item;
  get diagnostics v_capitulos = row_count;

  insert into public.questoes (
    disciplina_id, capitulo_id, tipo, enunciado, alternativas,
    resposta_correta, resolucao, dificuldade, fonte, ativo
  )
  select
    v_id,
    c.id,
    coalesce(nullif(q.item->>'tipo', ''), 'multipla_escolha'),
    q.item->>'enunciado',
    q.item->'alternativas',
    (q.item->>'resposta_correta')::smallint,
    q.item->>'resolucao',
    coalesce(nullif(q.item->>'dificuldade', ''), 'media'),
    nullif(q.item->>'fonte', ''),
    coalesce((q.item->>'ativo')::boolean, true)
  from jsonb_array_elements(coalesce(p_questoes, '[]'::jsonb)) as q(item)
  join public.capitulos c
    on c.disciplina_id = v_id
   and c.indice = (q.item->>'capitulo_indice')::integer;
  get diagnostics v_questoes = row_count;

  if v_questoes <> jsonb_array_length(coalesce(p_questoes, '[]'::jsonb)) then
    raise exception 'Nem todas as questões puderam ser vinculadas aos capítulos importados.';
  end if;

  return jsonb_build_object('disciplina_id', v_id, 'capitulos', v_capitulos, 'questoes', v_questoes);
end;
$$;

revoke all on function public.substituir_disciplina_completa(jsonb, jsonb, jsonb) from public;
grant execute on function public.substituir_disciplina_completa(jsonb, jsonb, jsonb) to service_role;
revoke all on public.ranking_usuarios from anon, authenticated;
grant select on public.ranking_usuarios to service_role;

-- v4.6: presença online e chat temporário.
create table if not exists public.presencas_online (
  usuario_id uuid primary key references public.usuarios(id) on delete cascade,
  visto_em timestamptz not null default now(),
  atividade_em timestamptz not null default now()
);

create table if not exists public.chat_temporario (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  mensagem text not null check (char_length(trim(mensagem)) between 1 and 400),
  criado_em timestamptz not null default now()
);

create index if not exists idx_presencas_online_visto_em on public.presencas_online(visto_em desc);
create index if not exists idx_presencas_online_atividade_em on public.presencas_online(atividade_em desc);
create index if not exists idx_chat_temporario_criado_em on public.chat_temporario(criado_em desc);

alter table public.presencas_online enable row level security;
alter table public.chat_temporario enable row level security;
revoke all on public.presencas_online from anon, authenticated;
revoke all on public.chat_temporario from anon, authenticated;
grant select, insert, update, delete on public.presencas_online to service_role;
grant select, insert, update, delete on public.chat_temporario to service_role;
grant usage, select on sequence public.chat_temporario_id_seq to service_role;

-- v4.8: cobranças Pix e liberação automática de acesso.
create table if not exists public.pagamentos (
  id uuid primary key,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  plano text not null check (plano in ('mensal', 'trimestral', 'vitalicio')),
  valor numeric(10,2) not null check (valor > 0),
  status text not null default 'pendente',
  mercado_pago_preference_id text unique,
  mercado_pago_payment_id text unique,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  aprovado_em timestamptz,
  aplicado_em timestamptz
);

create index if not exists idx_pagamentos_usuario_criado on public.pagamentos(usuario_id, criado_em desc);
create index if not exists idx_pagamentos_status on public.pagamentos(status, atualizado_em desc);
alter table public.pagamentos enable row level security;
revoke all on public.pagamentos from anon, authenticated;
grant select, insert, update on public.pagamentos to service_role;

create or replace function public.confirmar_pagamento_pix(
  p_pagamento_id uuid, p_mercado_pago_payment_id text, p_status text,
  p_valor_recebido numeric, p_moeda text, p_meio_pagamento text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pagamento public.pagamentos%rowtype;
  v_base timestamptz;
  v_nova_validade timestamptz;
begin
  select * into v_pagamento from public.pagamentos where id = p_pagamento_id for update;
  if not found then return jsonb_build_object('aplicado', false, 'motivo', 'pagamento_nao_encontrado'); end if;
  if v_pagamento.aplicado_em is not null then return jsonb_build_object('aplicado', false, 'motivo', 'ja_aplicado'); end if;

  if p_status <> 'approved' then
    update public.pagamentos set status = left(coalesce(p_status, 'desconhecido'), 40),
      mercado_pago_payment_id = coalesce(mercado_pago_payment_id, p_mercado_pago_payment_id), atualizado_em = now()
    where id = p_pagamento_id;
    return jsonb_build_object('aplicado', false, 'motivo', 'nao_aprovado');
  end if;

  if p_moeda <> 'BRL' or p_meio_pagamento <> 'pix' or p_valor_recebido <> v_pagamento.valor then
    update public.pagamentos set status = 'revisao', atualizado_em = now() where id = p_pagamento_id;
    return jsonb_build_object('aplicado', false, 'motivo', 'dados_divergentes');
  end if;

  if v_pagamento.plano = 'vitalicio' then
    update public.usuarios set vip = true, vip_desde = coalesce(vip_desde, now()), acesso_teste = false,
      teste_expira_em = null, validade_ate = null, status_aprovacao = 'aprovado', ativo = true,
      desativado_por_validade = false where id = v_pagamento.usuario_id;
  else
    select greatest(now(), coalesce(validade_ate, now())) into v_base
      from public.usuarios where id = v_pagamento.usuario_id for update;
    v_nova_validade := v_base + case v_pagamento.plano
      when 'mensal' then interval '30 days' when 'trimestral' then interval '90 days' end;
    update public.usuarios set vip = false, acesso_teste = false, teste_expira_em = null,
      validade_ate = v_nova_validade, status_aprovacao = 'aprovado', ativo = true,
      desativado_por_validade = false where id = v_pagamento.usuario_id;
  end if;

  update public.pagamentos set status = 'approved', mercado_pago_payment_id = p_mercado_pago_payment_id,
    atualizado_em = now(), aprovado_em = now(), aplicado_em = now() where id = p_pagamento_id;
  return jsonb_build_object('aplicado', true, 'plano', v_pagamento.plano, 'validade_ate', v_nova_validade);
end;
$$;

revoke all on function public.confirmar_pagamento_pix(uuid, text, text, numeric, text, text) from public;
grant execute on function public.confirmar_pagamento_pix(uuid, text, text, numeric, text, text) to service_role;

-- v4.25: duas sessoes simultaneas por aluno, uma por dispositivo.
create table if not exists public.sessoes_dispositivo (
  id uuid primary key,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  device_hash text not null check (device_hash ~ '^[a-f0-9]{64}$'),
  criada_em timestamptz not null default now(),
  ultimo_acesso_em timestamptz not null default now(),
  expira_em timestamptz not null,
  unique (usuario_id, device_hash)
);
create index if not exists sessoes_dispositivo_usuario_idx on public.sessoes_dispositivo(usuario_id, expira_em desc);
create index if not exists sessoes_dispositivo_expira_idx on public.sessoes_dispositivo(expira_em);
alter table public.sessoes_dispositivo enable row level security;
revoke all on public.sessoes_dispositivo from public, anon, authenticated;
grant all on public.sessoes_dispositivo to service_role;

create or replace function public.iniciar_sessao_dispositivo_aluno(
  p_usuario_id uuid, p_sessao_id uuid, p_expira_em timestamptz,
  p_device_hash text, p_limite integer default 2
)
returns table (permitido boolean, sessao_id uuid, sessoes_ativas integer, reutilizada boolean)
language plpgsql security definer set search_path = public
as $$
declare v_existente uuid; v_quantidade integer;
begin
  if p_limite < 1 or p_limite > 5 or p_device_hash !~ '^[a-f0-9]{64}$' or p_expira_em <= now() then
    return query select false, null::uuid, 0, false; return;
  end if;
  perform 1 from public.usuarios where id = p_usuario_id and perfil = 'aluno' for update;
  if not found then return query select false, null::uuid, 0, false; return; end if;
  delete from public.sessoes_dispositivo where usuario_id = p_usuario_id and expira_em <= now();
  select id into v_existente from public.sessoes_dispositivo
    where usuario_id = p_usuario_id and device_hash = p_device_hash and expira_em > now() limit 1;
  if v_existente is not null then
    update public.sessoes_dispositivo set expira_em = p_expira_em, ultimo_acesso_em = now() where id = v_existente;
    select count(*) into v_quantidade from public.sessoes_dispositivo where usuario_id = p_usuario_id and expira_em > now();
    return query select true, v_existente, v_quantidade, true; return;
  end if;
  select count(*) into v_quantidade from public.sessoes_dispositivo where usuario_id = p_usuario_id and expira_em > now();
  if v_quantidade >= p_limite then return query select false, null::uuid, v_quantidade, false; return; end if;
  insert into public.sessoes_dispositivo(id, usuario_id, device_hash, expira_em)
    values (p_sessao_id, p_usuario_id, p_device_hash, p_expira_em);
  return query select true, p_sessao_id, v_quantidade + 1, false;
end;
$$;
revoke all on function public.iniciar_sessao_dispositivo_aluno(uuid, uuid, timestamptz, text, integer) from public, anon, authenticated;
grant execute on function public.iniciar_sessao_dispositivo_aluno(uuid, uuid, timestamptz, text, integer) to service_role;
