create extension if not exists pgcrypto;

create table if not exists public.usuarios (
  id uuid primary key default gen_random_uuid(),
  usuario text not null unique check (usuario ~ '^[a-zA-Z0-9._-]{3,30}$'),
  senha_hash text not null,
  nome text not null,
  perfil text not null default 'aluno' check (perfil in ('supremo','admin','aluno')),
  ativo boolean not null default true,
  status_aprovacao text not null default 'pendente' check (status_aprovacao in ('pendente','aprovado','negado')),
  criado_em timestamptz not null default now(),
  ultimo_acesso timestamptz,
  validade_ate timestamptz,
  desativado_por_validade boolean not null default false,
  criado_por_admin_id uuid references public.usuarios(id) on delete set null,
  aprovado_por_admin_id uuid references public.usuarios(id) on delete set null,
  responsavel_admin_id uuid references public.usuarios(id) on delete set null,
  vip boolean not null default false,
  vip_desde timestamptz
);

create table if not exists public.disciplinas (
  id text primary key,
  nome text not null,
  descricao text,
  ordem integer not null default 0,
  ativo boolean not null default true
);

create table if not exists public.capitulos (
  id bigint generated by default as identity primary key,
  disciplina_id text not null references public.disciplinas(id) on delete cascade,
  indice integer not null,
  nome text not null,
  ativo boolean not null default true,
  unique (disciplina_id, indice)
);

create table if not exists public.questoes (
  id bigint generated by default as identity primary key,
  disciplina_id text not null references public.disciplinas(id),
  capitulo_id bigint not null references public.capitulos(id),
  tipo text not null default 'multipla_escolha' check (tipo in ('multipla_escolha','certo_errado')),
  enunciado text not null,
  alternativas jsonb not null check (jsonb_array_length(alternativas) between 2 and 5),
  resposta_correta smallint not null check (resposta_correta between 0 and 4),
  resolucao text not null,
  dificuldade text not null default 'media' check (dificuldade in ('facil','media','dificil')),
  fonte text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.sessoes (
  id uuid primary key default gen_random_uuid(),
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  disciplina_id text references public.disciplinas(id),
  capitulo_id bigint references public.capitulos(id) on delete set null,
  total integer not null default 0,
  respondidas integer not null default 0,
  acertos integer not null default 0,
  puladas integer not null default 0,
  percentual integer not null default 0,
  iniciada_em timestamptz not null default now(),
  finalizada_em timestamptz
);

create table if not exists public.respostas (
  id bigint generated by default as identity primary key,
  sessao_id uuid not null references public.sessoes(id) on delete cascade,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  questao_id bigint references public.questoes(id) on delete set null,
  resposta_marcada smallint check (resposta_marcada between 0 and 4),
  acertou boolean not null default false,
  pulada boolean not null default false,
  respondida_em timestamptz not null default now(),
  questao_enunciado text,
  questao_alternativas jsonb,
  questao_resposta_correta smallint,
  questao_resolucao text,
  disciplina_id_snapshot text,
  disciplina_nome_snapshot text,
  capitulo_id_snapshot bigint,
  capitulo_nome_snapshot text,
  unique(sessao_id, questao_id)
);

create index if not exists idx_questoes_filtro on public.questoes(disciplina_id, capitulo_id, ativo);
create index if not exists idx_sessoes_usuario on public.sessoes(usuario_id, finalizada_em desc);
create index if not exists idx_respostas_usuario on public.respostas(usuario_id, respondida_em desc);
create index if not exists idx_respostas_usuario_questao_recente on public.respostas(usuario_id, questao_id, respondida_em desc) where pulada = false;
create index if not exists idx_usuarios_responsavel_admin on public.usuarios(responsavel_admin_id);
create index if not exists idx_usuarios_vip on public.usuarios(vip) where vip = true;

alter table public.usuarios enable row level security;
alter table public.disciplinas enable row level security;
alter table public.capitulos enable row level security;
alter table public.questoes enable row level security;
alter table public.sessoes enable row level security;
alter table public.respostas enable row level security;

-- Nenhuma política pública é criada. O acesso ocorre somente pelas Netlify Functions
-- usando a chave service_role mantida em variável de ambiente.


-- v4.3: snapshot automático de respostas para preservar histórico após substituições.
create or replace function public.preencher_snapshot_resposta()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.questao_id is null then return new; end if;
  select q.enunciado, q.alternativas, q.resposta_correta, q.resolucao,
         q.disciplina_id, d.nome, q.capitulo_id, c.nome
    into new.questao_enunciado, new.questao_alternativas, new.questao_resposta_correta,
         new.questao_resolucao, new.disciplina_id_snapshot, new.disciplina_nome_snapshot,
         new.capitulo_id_snapshot, new.capitulo_nome_snapshot
  from public.questoes q
  left join public.disciplinas d on d.id = q.disciplina_id
  left join public.capitulos c on c.id = q.capitulo_id
  where q.id = new.questao_id;
  return new;
end;
$$;

create trigger trg_respostas_snapshot
before insert or update of questao_id on public.respostas
for each row execute function public.preencher_snapshot_resposta();

create or replace view public.ranking_usuarios as
select
  u.id as usuario_id,
  u.nome,
  u.usuario,
  u.perfil,
  u.vip,
  count(distinct r.sessao_id)::bigint as sessoes,
  count(r.id)::bigint as respondidas,
  count(r.id) filter (where r.acertou)::bigint as acertos,
  case when count(r.id) > 0
    then round((count(r.id) filter (where r.acertou))::numeric / count(r.id)::numeric * 100)::integer
    else 0 end as percentual
from public.usuarios u
join public.respostas r on r.usuario_id = u.id
where r.pulada = false and r.resposta_marcada is not null
group by u.id, u.nome, u.usuario, u.perfil, u.vip;

-- v4.3: substituição transacional de disciplina.
create or replace function public.substituir_disciplina_completa(
  p_disciplina jsonb,
  p_capitulos jsonb,
  p_questoes jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id text;
  v_capitulos integer := 0;
  v_questoes integer := 0;
begin
  v_id := nullif(trim(p_disciplina->>'id'), '');
  if v_id is null then raise exception 'Disciplina inválida.'; end if;

  insert into public.disciplinas (id, nome, descricao, ordem, ativo)
  values (
    v_id,
    p_disciplina->>'nome',
    nullif(p_disciplina->>'descricao', ''),
    coalesce((p_disciplina->>'ordem')::integer, 0),
    coalesce((p_disciplina->>'ativo')::boolean, true)
  )
  on conflict (id) do update set
    nome = excluded.nome,
    descricao = excluded.descricao,
    ordem = excluded.ordem,
    ativo = excluded.ativo;

  delete from public.questoes where disciplina_id = v_id;
  delete from public.capitulos where disciplina_id = v_id;

  insert into public.capitulos (disciplina_id, indice, nome, ativo)
  select v_id, (item->>'indice')::integer, item->>'nome', coalesce((item->>'ativo')::boolean, true)
  from jsonb_array_elements(coalesce(p_capitulos, '[]'::jsonb)) item;
  get diagnostics v_capitulos = row_count;

  insert into public.questoes (
    disciplina_id, capitulo_id, tipo, enunciado, alternativas,
    resposta_correta, resolucao, dificuldade, fonte, ativo
  )
  select
    v_id,
    c.id,
    coalesce(nullif(q.item->>'tipo', ''), 'multipla_escolha'),
    q.item->>'enunciado',
    q.item->'alternativas',
    (q.item->>'resposta_correta')::smallint,
    q.item->>'resolucao',
    coalesce(nullif(q.item->>'dificuldade', ''), 'media'),
    nullif(q.item->>'fonte', ''),
    coalesce((q.item->>'ativo')::boolean, true)
  from jsonb_array_elements(coalesce(p_questoes, '[]'::jsonb)) as q(item)
  join public.capitulos c
    on c.disciplina_id = v_id
   and c.indice = (q.item->>'capitulo_indice')::integer;
  get diagnostics v_questoes = row_count;

  if v_questoes <> jsonb_array_length(coalesce(p_questoes, '[]'::jsonb)) then
    raise exception 'Nem todas as questões puderam ser vinculadas aos capítulos importados.';
  end if;

  return jsonb_build_object('disciplina_id', v_id, 'capitulos', v_capitulos, 'questoes', v_questoes);
end;
$$;

revoke all on function public.substituir_disciplina_completa(jsonb, jsonb, jsonb) from public;
grant execute on function public.substituir_disciplina_completa(jsonb, jsonb, jsonb) to service_role;
revoke all on public.ranking_usuarios from anon, authenticated;
grant select on public.ranking_usuarios to service_role;
