create extension if not exists pgcrypto;

create table if not exists public.usuarios (
  id uuid primary key default gen_random_uuid(),
  usuario text not null unique check (usuario ~ '^[a-zA-Z0-9._-]{3,30}$'),
  senha_hash text not null,
  nome text not null,
  perfil text not null default 'aluno' check (perfil in ('admin','aluno')),
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  ultimo_acesso timestamptz
);

create table if not exists public.disciplinas (
  id text primary key,
  nome text not null,
  descricao text,
  ordem integer not null default 0,
  ativo boolean not null default true
);

create table if not exists public.capitulos (
  id bigint generated by default as identity primary key,
  disciplina_id text not null references public.disciplinas(id) on delete cascade,
  indice integer not null,
  nome text not null,
  ativo boolean not null default true,
  unique (disciplina_id, indice)
);

create table if not exists public.questoes (
  id bigint generated by default as identity primary key,
  disciplina_id text not null references public.disciplinas(id),
  capitulo_id bigint not null references public.capitulos(id),
  tipo text not null default 'multipla_escolha' check (tipo in ('multipla_escolha','certo_errado')),
  enunciado text not null,
  alternativas jsonb not null check (jsonb_array_length(alternativas) between 2 and 5),
  resposta_correta smallint not null check (resposta_correta between 0 and 4),
  resolucao text not null,
  dificuldade text not null default 'media' check (dificuldade in ('facil','media','dificil')),
  fonte text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.sessoes (
  id uuid primary key default gen_random_uuid(),
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  disciplina_id text references public.disciplinas(id),
  capitulo_id bigint references public.capitulos(id),
  total integer not null default 0,
  respondidas integer not null default 0,
  acertos integer not null default 0,
  puladas integer not null default 0,
  percentual integer not null default 0,
  iniciada_em timestamptz not null default now(),
  finalizada_em timestamptz
);

create table if not exists public.respostas (
  id bigint generated by default as identity primary key,
  sessao_id uuid not null references public.sessoes(id) on delete cascade,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  questao_id bigint not null references public.questoes(id),
  resposta_marcada smallint check (resposta_marcada between 0 and 4),
  acertou boolean not null default false,
  pulada boolean not null default false,
  respondida_em timestamptz not null default now(),
  unique(sessao_id, questao_id)
);

create index if not exists idx_questoes_filtro on public.questoes(disciplina_id, capitulo_id, ativo);
create index if not exists idx_sessoes_usuario on public.sessoes(usuario_id, finalizada_em desc);
create index if not exists idx_respostas_usuario on public.respostas(usuario_id, respondida_em desc);

alter table public.usuarios enable row level security;
alter table public.disciplinas enable row level security;
alter table public.capitulos enable row level security;
alter table public.questoes enable row level security;
alter table public.sessoes enable row level security;
alter table public.respostas enable row level security;

-- Nenhuma política pública é criada. O acesso ocorre somente pelas Netlify Functions
-- usando a chave service_role mantida em variável de ambiente.
